# Generated by Django 4.0.1 on 2022-03-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='Endereco',
            new_name='endereco',
        ),
    ]
