# Generated by Django 4.0.1 on 2022-03-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_categoria_descricao_alter_fornecedor_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descricao do produto'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='endereco do fornecedor'),
        ),
    ]
