# Generated by Django 4.0.3 on 2022-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_rename_nome_funcionario_nomefuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('SE', 'Servidor'), ('TE', 'Terceirizado')], max_length=15, verbose_name='Tipo'),
        ),
    ]
